[profile.default]
src = 'contracts'
solc = "./bin/solc"
out = 'out'
libs = ["node_modules", "lib"]
test = 'test/foundry'
remappings = [
    '@rari-capital/solmate/=lib/solmate/',
    'ds-test/=lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/',
    'murky/=lib/murky/src/',
    '@openzeppelin/=lib/openzeppelin-contracts/',
    'solarray/=lib/solarray/src/',
    'solady/=lib/solady/',
    'seaport-sol/=lib/seaport-sol/',
    'seaport-types/=lib/seaport-types/',
    'seaport-core/=lib/seaport-core/',
    'seaport/=contracts/'
]
optimizer_runs = 4_294_967_295
fs_permissions = [
    { access = "read", path = "./bin" },
    { access = "read", path = "./out" },
    { access = "read", path = "./optimized-out" },
    { access = "read", path = "./reference-out" },
    { access = "write", path = "./call-metrics.txt" },
    { access = "write", path = "./mutation-metrics.txt" },
    { access = "write", path = "./assume-metrics.txt" },
    { access = "write", path = "./fuzz_debug.json" }
]

# TODO: update this to the 1.6 branch instead of the tstore branch once stuff
#       starts getting merged into 1.6.
[profile.tstore-default]
solc = "./bin/solc"
cancun = true
via_ir = false
remappings = [
    '@rari-capital/solmate/=lib/solmate/',
    'ds-test/=lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/',
    'murky/=lib/murky/src/',
    '@openzeppelin/=lib/openzeppelin-contracts/',
    'solarray/=lib/solarray/src/',
    'solady/=lib/solady/',
    'seaport-sol/=lib/seaport-sol/',
    'seaport-types/=lib/seaport-types/',
    # This is the one that matters
    'seaport-core/=lib/seaport-core-tstore/',
    'seaport/=./contracts/',
]
fs_permissions = [
    { access = "read", path = "./bin" },
    { access = "read", path = "./out" },
    { access = "read", path = "./optimized-out" },
    { access = "read", path = "./reference-out" },
    { access = "write", path = "./call-metrics.txt" },
    { access = "write", path = "./mutation-metrics.txt" },
    { access = "write", path = "./assume-metrics.txt" },
    { access = "write", path = "./fuzz_debug.json" }
]
# Don't compile tests with 0.8.22 bc yul stack too dank.
test = 'test/foundry'
out = 'out'

[profile.tstore-optimized]
solc = "./bin/solc"
cancun = true
via_ir = true
# Fewer runs to move quicker for now.
optimizer_runs = 9_999_999
remappings = [
    '@rari-capital/solmate/=lib/solmate/',
    'ds-test/=lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/',
    'murky/=lib/murky/src/',
    '@openzeppelin/=lib/openzeppelin-contracts/',
    'solarray/=lib/solarray/src/',
    'solady/=lib/solady/',
    'seaport-sol/=lib/seaport-sol/',
    'seaport-types/=lib/seaport-types/',
    # This is the one that matters
    'seaport-core/=lib/seaport-core-tstore/',
    'seaport/=./contracts/',
]
# Don't compile tests with 0.8.22 bc yul stack too dank.
test ='contracts'
script = 'contracts'
out = 'optimized-out'
bytecode_hash = 'none'

[profile.ci-tstore-build-optimized]
solc = "./bin/solc-static-linux"
cancun = true
via_ir = true
# Fewer runs to move quicker for now.
optimizer_runs = 9_999_999
remappings = [
    '@rari-capital/solmate/=lib/solmate/',
    'ds-test/=lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/',
    'murky/=lib/murky/src/',
    '@openzeppelin/=lib/openzeppelin-contracts/',
    'solarray/=lib/solarray/src/',
    'solady/=lib/solady/',
    'seaport-sol/=lib/seaport-sol/',
    'seaport-types/=lib/seaport-types/',
    # This is the one that matters
    'seaport-core/=lib/seaport-core-tstore/',
    'seaport/=./contracts/',
]
# Don't compile tests with 0.8.22 bc yul stack too dank.
test ='contracts'
script = 'contracts'
out = 'optimized-out'

[profile.ci-tstore]
src = 'test/foundry'
via_ir = false
solc = "./bin/solc-static-linux"
cancun = true
remappings = [
    '@rari-capital/solmate/=lib/solmate/',
    'ds-test/=lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/',
    'murky/=lib/murky/src/',
    '@openzeppelin/=lib/openzeppelin-contracts/',
    'solarray/=lib/solarray/src/',
    'solady/=lib/solady/',
    'seaport-sol/=lib/seaport-sol/',
    'seaport-types/=lib/seaport-types/',
    'seaport-core/=lib/seaport-core-tstore/',
    'seaport/=./contracts/'
]

[profile.validator]
solc = '0.8.17'
src = 'contracts/helpers/order-validator'
optimizer_runs = 1

[fuzz]
runs = 1_000
max_test_rejects = 1_000_000

[profile.reference]
solc = '0.8.13'
src = 'reference'
out = 'reference-out'
script = 'reference'
# specify something so it doesn't try to compile the 0.8.17 files in test/foundry
test = 'reference'

[profile.optimized]
via_ir = true
out = 'optimized-out'
script = 'contracts'
bytecode_hash = 'none'
# no need to compile tests with via-ir since they load optimized bytecode directly by default
test ='contracts'

[profile.test]
src = 'test/foundry'

[profile.test.fuzz]
runs = 1_000

[profile.lite]
out = 'optimized-out'

[profile.debug]
src = 'contracts'
optimizer = false

[profile.moat_debug]
optimizer = false
test = 'test/foundry/new'

[profile.offerers]
src='offerers'
test='offerers'
out = 'offerers-out'
script = 'offerers'

[fmt]
line_length = 80
tab_width = 4
bracket_spacing = true

# See more config options https://github.com/gakonst/foundry/tree/master/config
